// ============================================
// HeartQuest Items - Sci-Fi Fantasy Database
// ============================================

import { Item } from '../types';

export const ITEMS: Record<string, Item> = {
  // ============ WEAPONS ============
  plasma_dagger: {
    id: 'plasma_dagger',
    name: 'Plasma Dagger',
    description: 'A blade of pure plasma energy. Hums with barely contained power.',
    rarity: 'common',
    icon: '🗡️',
    type: 'weapon',
    stats: { attack: 5, speed: 2 },
    goldValue: 50,
  },
  neon_katana: {
    id: 'neon_katana',
    name: 'Neon Katana',
    description: 'A traditional blade infused with cyber-tech. Cuts through both armor and vibes.',
    rarity: 'uncommon',
    icon: '⚔️',
    type: 'weapon',
    stats: { attack: 12, speed: 5 },
    effect: { type: 'critical', value: 10 },
    goldValue: 200,
  },
  void_whip: {
    id: 'void_whip',
    name: 'Void Whip',
    description: 'A tendril of solidified nothing. Strikes from unexpected angles.',
    rarity: 'rare',
    icon: '🔥',
    type: 'weapon',
    stats: { attack: 18, speed: 8, luck: 3 },
    effect: { type: 'stun', duration: 2 },
    goldValue: 600,
  },
  crystal_staff: {
    id: 'crystal_staff',
    name: 'Crystal Staff',
    description: 'A staff of crystallized starlight. Channels arcane energy into devastating blasts.',
    rarity: 'rare',
    icon: '🔮',
    type: 'weapon',
    stats: { attack: 15, charisma: 10 },
    effect: { type: 'burn', value: 5, duration: 3 },
    goldValue: 550,
  },
  quantum_cleaver: {
    id: 'quantum_cleaver',
    name: 'Quantum Cleaver',
    description: 'Exists in multiple dimensions simultaneously. Each swing hits from all of them.',
    rarity: 'epic',
    icon: '⚡',
    type: 'weapon',
    stats: { attack: 30, speed: 10 },
    effect: { type: 'critical', value: 25 },
    goldValue: 2500,
  },
  soul_reaver: {
    id: 'soul_reaver',
    name: 'Soul Reaver',
    description: 'An ancient blade that feeds on the essence of defeated foes.',
    rarity: 'legendary',
    icon: '💀',
    type: 'weapon',
    stats: { attack: 50, speed: 15, luck: 10 },
    effect: { type: 'lifesteal', value: 20 },
    goldValue: 10000,
  },
  
  // ============ ARMOR ============
  dataweave_vest: {
    id: 'dataweave_vest',
    name: 'Dataweave Vest',
    description: 'Woven from fiber-optic threads. Light as code, tough as steel.',
    rarity: 'common',
    icon: '🥋',
    type: 'armor',
    stats: { defense: 5, health: 20 },
    goldValue: 40,
  },
  runic_exoskeleton: {
    id: 'runic_exoskeleton',
    name: 'Runic Exoskeleton',
    description: 'Magical runes carved into military-grade alloy. The old ways meet the new.',
    rarity: 'uncommon',
    icon: '🦾',
    type: 'armor',
    stats: { defense: 12, health: 50, speed: -2 },
    goldValue: 180,
  },
  phantom_cloak: {
    id: 'phantom_cloak',
    name: 'Phantom Cloak',
    description: 'Woven from shadow-stuff. Makes you harder to hit, harder to find.',
    rarity: 'rare',
    icon: '🧥',
    type: 'armor',
    stats: { defense: 8, speed: 10, detection: 15 },
    effect: { type: 'stealth', duration: 10 },
    goldValue: 700,
  },
  dragonscale_mesh: {
    id: 'dragonscale_mesh',
    name: 'Dragonscale Mesh',
    description: 'Scales from a techno-dragon, stitched into flexible armor. Fire? Electricity? Same thing.',
    rarity: 'epic',
    icon: '🐉',
    type: 'armor',
    stats: { defense: 25, health: 100, speed: 5 },
    goldValue: 3000,
  },
  aether_heart_shield: {
    id: 'aether_heart_shield',
    name: 'Aether Heart Shield',
    description: 'A crystallized fragment of the first star. Protects both body and soul.',
    rarity: 'legendary',
    icon: '💗',
    type: 'armor',
    stats: { defense: 40, health: 200, charisma: 20 },
    effect: { type: 'shield', value: 50 },
    goldValue: 15000,
  },
  
  // ============ ACCESSORIES ============
  holo_ring: {
    id: 'holo_ring',
    name: 'Holo-Ring',
    description: 'A ring that projects convincing holograms. Great for magic tricks and distractions.',
    rarity: 'common',
    icon: '💍',
    type: 'accessory',
    stats: { charisma: 5 },
    goldValue: 30,
  },
  neural_implant: {
    id: 'neural_implant',
    name: 'Neural Implant',
    description: 'A chip in your brain that processes threats faster. Gamer reflexes, but real.',
    rarity: 'uncommon',
    icon: '🧠',
    type: 'accessory',
    stats: { speed: 8, detection: 5 },
    goldValue: 150,
  },
  cloister_amulet: {
    id: 'cloister_amulet',
    name: 'Cloister Amulet',
    description: 'A charm of ancient protection. The spirits within watch over you.',
    rarity: 'rare',
    icon: '📿',
    type: 'accessory',
    stats: { health: 30, luck: 10 },
    goldValue: 500,
  },
  // THE LEGENDARY CLOAK OF DECEPTION
  cloak_of_deception: {
    id: 'cloak_of_deception',
    name: 'Cloak of Deception',
    description: 'An ancient artifact that masks your true intentions. Appear friendly while remaining hostile. Rivals won\'t know until it\'s too late.',
    rarity: 'legendary',
    icon: '🎭',
    type: 'accessory',
    stats: { charisma: 30, luck: 15 },
    effect: { type: 'stealth', duration: 60 },
    goldValue: 25000,
  },
  
  // ============ CONSUMABLES ============
  nano_potion: {
    id: 'nano_potion',
    name: 'Nano-Potion',
    description: 'Tiny robots swarm your wounds. It tickles, but you\'ll live.',
    rarity: 'common',
    icon: '🧪',
    type: 'consumable',
    uses: 1,
    stats: { health: 50 },
    effect: { type: 'heal', value: 50 },
    goldValue: 25,
  },
  quantum_food: {
    id: 'quantum_food',
    name: 'Quantum Food',
    description: 'Exists as all possible meals until observed. Tastes like whatever you crave.',
    rarity: 'uncommon',
    icon: '🍎',
    type: 'consumable',
    uses: 1,
    effect: { type: 'heal', value: 100 },
    goldValue: 60,
  },
  xp_boost_chip: {
    id: 'xp_boost_chip',
    name: 'XP Boost Chip',
    description: 'Temporarily accelerates neural pathways. Learn faster, level harder.',
    rarity: 'uncommon',
    icon: '📈',
    type: 'consumable',
    uses: 1,
    effect: { type: 'boost_xp', value: 50, duration: 1800 },
    goldValue: 100,
  },
  gold_magnet: {
    id: 'gold_magnet',
    name: 'Gold Magnet',
    description: 'Not actual gold. Attracts lucky drops for a limited time.',
    rarity: 'rare',
    icon: '🧲',
    type: 'consumable',
    uses: 1,
    effect: { type: 'boost_gold', value: 100, duration: 1800 },
    goldValue: 200,
  },
  
  // ============ SPECIAL ITEMS (Founder Rewards) ============
  dragons_heart: {
    id: 'dragons_heart',
    name: "Dragon's Heart Token",
    description: 'A crystallized heart of a techno-dragon. Grants massive stat boosts and marks you as a Founder. Forever in your inventory.',
    rarity: 'mythic',
    icon: '💗',
    type: 'special',
    stats: { health: 100, attack: 10, defense: 10, charisma: 20, luck: 15 },
    goldValue: 0, // Cannot be sold
  },
  prism_whistle: {
    id: 'prism_whistle',
    name: 'Prism Whistle',
    description: 'Summons a prism wolf companion. Legend says they guide lonely hearts to their matches.',
    rarity: 'legendary',
    icon: '🐺',
    type: 'special',
    stats: { detection: 30, luck: 20 },
    goldValue: 0,
  },
  cosmic_compass: {
    id: 'cosmic_compass',
    name: 'Cosmic Compass',
    description: 'Points toward destiny. Or the nearest rare monster. Hard to tell sometimes.',
    rarity: 'legendary',
    icon: '🧭',
    type: 'special',
    stats: { detection: 50 },
    effect: { type: 'reveal', duration: 30 },
    goldValue: 0,
  },
  
  // ============ MATERIALS ============
  monster_core: {
    id: 'monster_core',
    name: 'Monster Core',
    description: 'A crystallized essence dropped by defeated monsters. Used in crafting.',
    rarity: 'common',
    icon: '💎',
    type: 'material',
    goldValue: 10,
  },
  rare_essence: {
    id: 'rare_essence',
    name: 'Rare Essence',
    description: 'Concentrated power from powerful foes. Glows with inner light.',
    rarity: 'uncommon',
    icon: '✨',
    type: 'material',
    goldValue: 50,
  },
  stellar_shard: {
    id: 'stellar_shard',
    name: 'Stellar Shard',
    description: 'A fragment of a fallen star. Warm to the touch, humming with potential.',
    rarity: 'rare',
    icon: '⭐',
    type: 'material',
    goldValue: 200,
  },
};

export const getItemById = (id: string): Item | undefined => ITEMS[id];
export const getItemsByRarity = (rarity: Item['rarity']): Item[] => 
  Object.values(ITEMS).filter(item => item.rarity === rarity);
export const getItemsByType = (type: Item['type']): Item[] =>
  Object.values(ITEMS).filter(item => item.type === type);
